services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: no
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  adminer:
    image: adminer:latest
    restart: no
    ports:
      - 8888:8080